<?php
/**
 * @category Scandi
 * @package Scandi\Gtm
 * @author Oleksii Tsebinoga <aleksejt@scandiweb.com>
 * @copyright Copyright (c) 2017 Scandiweb, Ltd (http://scandiweb.com)
 * @license http://opensource.org/licenses/afl-3.0.php Academic Free License (AFL 3.0)
 */

/** @var $block \Scandi\Gtm\Block\Gtm */
?>

<?= $block->getGtm('head'); ?>

<!-- Product grid -->
<script>
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function () {
            getGeneralData();
            getCartUpdatePush();
            var i = 1;
            var items = jQuery('<?php echo $block->configHelper->getCategoryWrapper(); ?>');
            if (items) {
                items.each(
                    function () {
                        var el = jQuery(this);
                        el.click(function (event) {
                            productClick(this);
                        });
                        el.attr('number', i);
                        i++;
                    }
                );
            }
        });

        /**
         * Handle product click and push it to the layer
         * @param el
         * @returns {boolean}
         */
        function productClick(el) {
            var clickedProduct = jQuery(el).attr('number');
            var i, len;
            for (i = 0, len = dataLayer.length - 1; i < len; i++) {
                if (!dataLayer[i]["ecommerce"]) {
                    continue;
                }
                if (!dataLayer[i]["ecommerce"]["impressions"]) {
                    continue;
                }
                for (var j = 0, length = dataLayer[i]["ecommerce"]["impressions"].length; j < length; j++) {
                    if (dataLayer[i]["ecommerce"]["impressions"][j].position != clickedProduct) {
                        continue;
                    }
                    var product = dataLayer[i]["ecommerce"]["impressions"][j];
                    dataLayer.push({
                        "event": "productClick",
                        "ecommerce": {
                            "click": {
                                "actionField": {
                                    "list": product.list
                                },
                                "products": [{
                                    "id": product.id,
                                    "name": product.name,
                                    "price": product.price,
                                    "category": product.category,
                                    "position": product.position
                                }]
                            }
                        }
                    });
                    return true;
                }
            }
            return false;
        }

        /**
         * Handle ajax to get data for the dataLayer
         * @param urlPart
         */
        function getDataForPush(urlPart) {
            $.ajax({
                url: '<?= $block->getBaseUrl() ?>' + urlPart,
                type: "POST",
                showLoader: false,
                dataType: "json",
                data: {"page": "<?= $block->request->getFullActionName() ?>", "isMain": "<?= $block->logo->isHomePage() ?>"},
                success: function(responce) {
                    if (typeof(dataLayer) === 'undefined') {
                        return false;
                    }
                    if (responce) {
                        dataLayer.push(JSON.parse(responce));
                    }
                }
            });
        }

        /**
         * Serve the controller url to get cart events
         */
        function getCartUpdatePush() {
            getDataForPush('gtm/index/cart');
        }

        /**
         * Serve the controller url to get general layer
         */
        function getGeneralData() {
            getDataForPush('gtm/index/general');
        }
    });
</script>
